/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";
import { ActualError } from "./actual-error.js";

export type InvalidEmailResponseErrorData = {
  error: models.InvalidEmailResponseErrorUnion;
};

export class InvalidEmailResponseError extends ActualError {
  error: models.InvalidEmailResponseErrorUnion;

  /** The original data that was passed to this error instance. */
  data$: InvalidEmailResponseErrorData;

  constructor(
    err: InvalidEmailResponseErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "InvalidEmailResponseError";
  }
}

/** @internal */
export const InvalidEmailResponseError$inboundSchema: z.ZodMiniType<
  InvalidEmailResponseError,
  unknown
> = z.pipe(
  z.object({
    error: z.lazy(() => models.InvalidEmailResponseErrorUnion$inboundSchema),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new InvalidEmailResponseError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
