/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";
import { ActualError } from "./actual-error.js";

export type WaitlistUnavailableResponseErrorData = {
  error: models.WaitlistUnavailableResponseErrorUnion;
};

export class WaitlistUnavailableResponseError extends ActualError {
  error: models.WaitlistUnavailableResponseErrorUnion;

  /** The original data that was passed to this error instance. */
  data$: WaitlistUnavailableResponseErrorData;

  constructor(
    err: WaitlistUnavailableResponseErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "WaitlistUnavailableResponseError";
  }
}

/** @internal */
export const WaitlistUnavailableResponseError$inboundSchema: z.ZodMiniType<
  WaitlistUnavailableResponseError,
  unknown
> = z.pipe(
  z.object({
    error: z.lazy(() =>
      models.WaitlistUnavailableResponseErrorUnion$inboundSchema
    ),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new WaitlistUnavailableResponseError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
