/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Waitlist } from "./waitlist.js";

export class Actual extends ClientSDK {
  private _waitlist?: Waitlist;
  get waitlist(): Waitlist {
    return (this._waitlist ??= new Waitlist(this._options));
  }
}
