/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { waitlistJoinWaitlist } from "../funcs/waitlist-join-waitlist.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Waitlist extends ClientSDK {
  /**
   * Join the early-access waitlist
   *
   * @remarks
   * Registers an email address for Actual early access. Repeated addresses return the same response and do not reveal prior membership.
   */
  async joinWaitlist(
    request: models.JoinWaitlistRequest,
    options?: RequestOptions,
  ): Promise<models.JoinWaitlistResponse> {
    return unwrapAsync(waitlistJoinWaitlist(
      this,
      request,
      options,
    ));
  }
}
