/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the @rikalabs/actual SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx waitlistJoinWaitlist.example.ts
 */

import { Actual } from "@rikalabs/actual";

const actual = new Actual();

async function main() {
  const result = await actual.waitlist.joinWaitlist({
    email: "Dante21@gmail.com",
    source: "landing",
  });

  console.log(result);
}

main().catch(console.error);
