/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const ErrorInvalidJSON = {
  InvalidJson: "invalid_json",
} as const;
export type ErrorInvalidJSON = ClosedEnum<typeof ErrorInvalidJSON>;

export type InvalidJsonResponseErrorUnion = ErrorInvalidJSON;

/** @internal */
export const ErrorInvalidJSON$inboundSchema: z.ZodMiniEnum<
  typeof ErrorInvalidJSON
> = z.enum(ErrorInvalidJSON);

/** @internal */
export const InvalidJsonResponseErrorUnion$inboundSchema: z.ZodMiniType<
  InvalidJsonResponseErrorUnion,
  unknown
> = ErrorInvalidJSON$inboundSchema;

export function invalidJsonResponseErrorUnionFromJSON(
  jsonString: string,
): SafeParseResult<InvalidJsonResponseErrorUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InvalidJsonResponseErrorUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InvalidJsonResponseErrorUnion' from JSON`,
  );
}
