/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const ErrorInvalidEmail = {
  InvalidEmail: "invalid_email",
} as const;
export type ErrorInvalidEmail = ClosedEnum<typeof ErrorInvalidEmail>;

export type InvalidEmailResponseErrorUnion = ErrorInvalidEmail;

/** @internal */
export const ErrorInvalidEmail$inboundSchema: z.ZodMiniEnum<
  typeof ErrorInvalidEmail
> = z.enum(ErrorInvalidEmail);

/** @internal */
export const InvalidEmailResponseErrorUnion$inboundSchema: z.ZodMiniType<
  InvalidEmailResponseErrorUnion,
  unknown
> = ErrorInvalidEmail$inboundSchema;

export function invalidEmailResponseErrorUnionFromJSON(
  jsonString: string,
): SafeParseResult<InvalidEmailResponseErrorUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InvalidEmailResponseErrorUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InvalidEmailResponseErrorUnion' from JSON`,
  );
}
