/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export const SourceEnum = {
  Landing: "landing",
} as const;
export type SourceEnum = ClosedEnum<typeof SourceEnum>;

export type Source = SourceEnum;

export type JoinWaitlistRequest = {
  email: string;
  source: SourceEnum;
};

/** @internal */
export const SourceEnum$outboundSchema: z.ZodMiniEnum<typeof SourceEnum> = z
  .enum(SourceEnum);

/** @internal */
export type Source$Outbound = string;

/** @internal */
export const Source$outboundSchema: z.ZodMiniType<Source$Outbound, Source> =
  SourceEnum$outboundSchema;

export function sourceToJSON(source: Source): string {
  return JSON.stringify(Source$outboundSchema.parse(source));
}

/** @internal */
export type JoinWaitlistRequest$Outbound = {
  email: string;
  source: string;
};

/** @internal */
export const JoinWaitlistRequest$outboundSchema: z.ZodMiniType<
  JoinWaitlistRequest$Outbound,
  JoinWaitlistRequest
> = z.object({
  email: z.string(),
  source: SourceEnum$outboundSchema,
});

export function joinWaitlistRequestToJSON(
  joinWaitlistRequest: JoinWaitlistRequest,
): string {
  return JSON.stringify(
    JoinWaitlistRequest$outboundSchema.parse(joinWaitlistRequest),
  );
}
