/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const StatusEnum = {
  Joined: "joined",
} as const;
export type StatusEnum = ClosedEnum<typeof StatusEnum>;

export type Status = StatusEnum;

export type JoinWaitlistResponse = {
  status: StatusEnum;
};

/** @internal */
export const StatusEnum$inboundSchema: z.ZodMiniEnum<typeof StatusEnum> = z
  .enum(StatusEnum);

/** @internal */
export const Status$inboundSchema: z.ZodMiniType<Status, unknown> =
  StatusEnum$inboundSchema;

export function statusFromJSON(
  jsonString: string,
): SafeParseResult<Status, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Status$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Status' from JSON`,
  );
}

/** @internal */
export const JoinWaitlistResponse$inboundSchema: z.ZodMiniType<
  JoinWaitlistResponse,
  unknown
> = z.object({
  status: StatusEnum$inboundSchema,
});

export function joinWaitlistResponseFromJSON(
  jsonString: string,
): SafeParseResult<JoinWaitlistResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => JoinWaitlistResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'JoinWaitlistResponse' from JSON`,
  );
}
