/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const ErrorUnavailable = {
  Unavailable: "unavailable",
} as const;
export type ErrorUnavailable = ClosedEnum<typeof ErrorUnavailable>;

export type WaitlistUnavailableResponseErrorUnion = ErrorUnavailable;

/** @internal */
export const ErrorUnavailable$inboundSchema: z.ZodMiniEnum<
  typeof ErrorUnavailable
> = z.enum(ErrorUnavailable);

/** @internal */
export const WaitlistUnavailableResponseErrorUnion$inboundSchema: z.ZodMiniType<
  WaitlistUnavailableResponseErrorUnion,
  unknown
> = ErrorUnavailable$inboundSchema;

export function waitlistUnavailableResponseErrorUnionFromJSON(
  jsonString: string,
): SafeParseResult<WaitlistUnavailableResponseErrorUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      WaitlistUnavailableResponseErrorUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WaitlistUnavailableResponseErrorUnion' from JSON`,
  );
}
